name: anemia_assessment
description: Anemia Risk Assessment System
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.0
  flutter_tts: ^4.0.2
  pdf: ^3.11.1
  printing: ^5.13.4
  fl_chart: ^0.69.2
  shared_preferences: ^2.3.3
  share_plus: ^10.1.2
  geolocator: ^13.0.2
  google_sign_in: ^6.2.1
  google_sign_in_web: ^0.12.4+4
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  url_launcher: ^6.3.1
  flutter_local_notifications: ^18.0.1
  timezone: ^0.9.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true